env:
    node: true
    es6: true
    mocha: true

extends: 'eslint:recommended'

parser: 'babel-eslint'

parserOptions:
    ecmaVersion: 6
    sourceType: 'module'
    ecmaFeatures:
        jsx: true
        modules: true
        experimentalObjectRestSpread: true

rules:
    handle-callback-err: 2
    no-debugger: 2
    no-fallthrough: 2
    eol-last: 1
    no-irregular-whitespace: 1
    no-mixed-spaces-and-tabs: [1, smart-tabs]
    no-trailing-spaces: 1
    no-new-require: 2
    no-undef: 2
    no-unreachable: 2
    no-unused-vars: [1, { 'vars': 'all', 'args': 'none' }]
    no-console: 2
    max-len: [2, 150, 4]
    prefer-arrow-callback:
        - error
        - allowNamedFunctions: true
    indent:
        - error
        - 2
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-lonely-if: 2
    no-else-return: 2
    no-empty-function: 1
    no-eq-null: 2
    no-var: 2
    strict:
        - error
        - global